version: '{branch}-{build}'

before_build:
  - nuget restore

build:
  project: MLAPI.sln
  verbosity: minimal

before_package:
  - powershell "& ""C:\projects\mlapi\BuildUnityPackages.ps1"""

artifacts:
  - path: 'MLAPI\bin\Debug\MLAPI*'
  - path: '*.unitypackage'


image: Visual Studio 2017

test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI.Tests\bin\Debug\MLAPI.Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI.Tests*]* "


after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 
