version: '{branch}-{build}'

configuration:
  - Debug
  - Release
  - Release_Lite
  - Debug_Lite

skip_commits:
  files:
    - docs/*

before_build:
  - nuget restore

build:
  project: MLAPI.sln
  verbosity: minimal

before_package:
  - cd C:\projects\mlapi
  - powershell "& "".\BuildUnityPackages.ps1"""

artifacts:
  - path: '*.unitypackage'

image: Visual Studio 2017


for:
-
  matrix:
    only:
      - configuration: Debug
  test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Debug\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Debug\MLAPI*'
-
  matrix:
    only:
      - configuration: Debug_Lite
  test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Lite\Debug\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Debug\Lite\MLAPI*'
-
  matrix:
    only:
      - configuration: Release
  test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Release\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Release\MLAPI*'
-
  matrix:
    only:
      - configuration: Release_Lite
  test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Lite\Release\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Release\Lite\MLAPI*'


after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 