version: '{branch}-{build}'

configuration:
  - Debug
  - Debug_Lite
  - Release_Lite
  - Release

skip_commits:
  files:
    - docs/*

skip_tags: true

build:
  project: MLAPI.sln
  verbosity: minimal

before_package:
  - cd C:\projects\mlapi
  - powershell "& "".\BuildUnityPackages.ps1"""

artifacts:
  - path: '*.unitypackage'

image: Visual Studio 2017

before_build:
  - nuget restore

matrix:
  fast_finish: true

for:
-
  matrix:
    only:
      - configuration: Debug
  artifacts:
  - path: 'MLAPI\bin\Debug\*\*MLAPI*'
  after_build:
  - cp MLAPI/bin/Debug/net35/*MLAPI* C:\projects\mlapi\MLAPI\bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Debug\*\MLAPI-Tests.dll'
-
  matrix:
    only:
      - configuration: Debug_Lite
  artifacts:
  - path: 'MLAPI\bin\Lite\Debug\*\*MLAPI*'
  after_build:
  - cp MLAPI/bin/Lite/Debug/net35/*MLAPI* C:\projects\mlapi\MLAPI\bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Lite\Debug\*\MLAPI-Tests.dll'
-
  matrix:
    only:
      - configuration: Release
  artifacts:
  - path: 'MLAPI\bin\Release\*\*MLAPI*'
  after_build:
  - cp MLAPI/bin/Release/net35/*MLAPI* C:\projects\mlapi\MLAPI\bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Release\*\MLAPI-Tests.dll'
  cache:
  - '%APPDATA%\npm'
  install:
  - npm install -g semantic-release
  deploy_script:
  - semantic-release
-
  matrix:
    only:
      - configuration: Release_Lite
  artifacts:
  - path: 'MLAPI\bin\Lite\Release\*\*MLAPI*'
  after_build:
  - cp MLAPI/bin/Lite/Release/net35/*MLAPI* C:\projects\mlapi\MLAPI\bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Lite\Release\*\MLAPI-Tests.dll'